### ISSUE TITLE
Possible speed up of StPicoUtilities::calculateRefMult()

### ISSUE THREAD

**Issue by plexoos** [rnc-lbl/star-picoDst#68]
While looking at `picoDst` code I noticed that `StPicoUtilities::calculateRefMult()` creates and fills a map of track multiplicities indexed by strings. Using strings for map element look up in general is less efficient than using int's. Since the look up is done a few times per track I suspect it can significantly affect the performance. I suggest we switch to `int` keys or perhaps even better to a fixed size std::array since the size of the created array is known in advance.

@xuji19891014 Can you have a look please? 

https://github.com/star-bnl/star-picoDst/blob/master/StPicoEvent/StPicoUtilities.h

**Comment by MustafaMustafa** [comment]
That is true in theory. I suggest to profile (an emulation) to check if the difference in performance between string and ints matters in this case. Can you test with an emulation code?

I suggested the strings for code clarity and for maintainability. If you introduce ints you will need to maintain those across two files. Or introduce some enum that is accessible in both files. IMHO, unnecessary complexity if the gain in performance is negligible.

**Comment by plexoos** [comment]
By int's I mean enum's of course which provide the convenience. Not sure how enum is less clear and maintainable or can introduce more complexity than strings... Don't you agree that a map is a more complex object than a simple array? Why use a map then if array is enough?

> If you introduce ints you will need to maintain those across two files.

Which two files?

**Comment by veprbl** [comment]
benchmarks!

**Comment by veprbl** [comment]
I'd think the bottleneck would rather be the string concatenation if one uses this style as in the code linked: `"refMult2" + chargeName + tpcHalfName`

**Comment by MustafaMustafa** [comment]
@plexoos 

> Which two files?

StPicoEvent.cxx and StPicoUtilities.h. The other option is to introduce a local array with enum indices and still return a map. 

By the way, if you introduce an array you will have at least three multi branches if-else statements. You will need at least 50 more lines to implement your suggestions. I am just wondering if it is worth it :-)

What I meant by code complexity is syntax complexity not performance.

**Comment by plexoos** [comment]
Benchmarking is fine. But there is also such a thing as experience and it is kind of not smart to ignore it... well if you have it :) It is obvious that any manipulation with strings will require more resources than the same with numbers. You can benchmark to get exact numbers but it is a fact: strings are slower. I would never use strings for anything other than interacting with a human.

The problem in question is just a problem of 16 counters! 16 counters Carl! :) why strings? why map with its allocation in the heap or god knows what?

> By the way, if you introduce an array you will have to at least three multi branches if-else statements. You will need at least 50 more lines to implement your suggestions. I am just wondering if it is worth it :-)

I don't know what you have in mind but I don't think so... Ok, I thought it could be a good exercise for a student but if you gentlemen insist I can come up with some code... later

**Comment by MustafaMustafa** [comment]
Hi @plexoos, 
It is obvious that strings are slower than ints. That is not what we are discussing. How slower is the question? It is a matter of trade-offs between code clarity and speed. 

> I don't know what you have in mind but I don't think so... Ok, I thought it could be a good exercise for a student but if you gentlemen insist I can come up with some code... later

@xuji19891014  implemented the code in arrays previously. I asked him to switch to an unordered_map. Code readability and maintainability is always more important for me (at a reasonable resources cost). 

By the way, you will know what I have in mind when you try to implement it ;-)

**Comment by plexoos** [comment]
I tried to search but could not find the version with arrays. There is one with separate loops and routines for each multiplicity type but that one was already replaced by the single loop with the map. Anyway, let me show what I have in mind and then you tell me if it less maintainable and why :)

**Comment by MustafaMustafa** [comment]
That would be great, then we can also do a binary test of the performance.

--Mustafa

**Comment by plexoos** [comment]
will that work? https://github.com/star-bnl/star-picoDst/commit/3b8e35df88b7cf95c3e63729144c46193af5f001

**Comment by MustafaMustafa** [comment]
Hi @plexoos, 

This is awesome actually, I didn't think of the encoding idea. Thank you. 

Can you
1) Add a comment about the encoding scheme you use for future developers and code readers (it takes a few minutes to parse in head). 
2) Compare the performance to the map implementation? (This is will be my lesson learned, appreciate it).

**Comment by plexoos** [comment]
Ok, cool! Now you have to endorse me on linkedin :)

Actually, in this case we got a bit lucky because the categories (Neg/Pos, East/West) nicely fall into the binary scheme. With a different "binning" (or number of "bins") of the 16 categories I think the encoding would not be so straight forward, i.e. one would need to come up with more tricks to encode all cases in a contiguous range of numbers to be used as array indices... In any case, an int-to-int map should be preferred over a string-to-int.

Sure, I'll add more comments and clean up for the master branch. In fact, I feel like switching to strongly typed enums instead... Yes, they would require an explicit conversion to int but... Also, what about moving the function from the .h to a cxx file? Was there a specific reason for placing it in a header?

Yes, we should benchmark it to confirm. Do you know if Ji Xu is around and available? I wouldn't like to steal a credit for what looks like a nice two-hour project for a student :)

**Comment by MustafaMustafa** [comment]
I am not sure about @xuji19891014 

P.S. You don't have C++ on your list of skills on Linkedin :-)
