### ISSUE TITLE
Mysterious condition in MTD related code

### ISSUE THREAD

**Issue by plexoos** [rnc-lbl/star-picoDst#69]
Coverity says the following conditions are always false which is certainly correct:

https://github.com/star-bnl/star-picoDst/commit/f229417d2d5db4dc20b25fe161d966187bba532b#diff-481a5a372b1acc89c4239f3e8f059659R37
https://github.com/star-bnl/star-picoDst/commit/f229417d2d5db4dc20b25fe161d966187bba532b#diff-b93c9ff2d7dd217e723c032aebc4b5e4R223

**Comment by veprbl** [comment]
The code introduced in https://github.com/star-bnl/star-picoDst/commit/2576a85e51381e8852f04767ba4a27364ae2d91c by @marrbnl 
The false value should not practically matter because we don't run in December anyways. Also, fiscal year starts October 1st, not December 1st.

**Comment by marrbnl** [comment]
Thanks for pointing this to me. Both issues are fixed now
https://github.com/star-bnl/star-picoDst/pull/66/commits/de99dd66a86c7d7b6262c343ed1b7431d12dd4bf

**Comment by plexoos** [comment]
Looks good to me. Thank you guys!
